// Auto-generated by build.js — DO NOT EDIT MANUALLY
// Environment variables injected at build time.
// Only Supabase is injected into the browser; third-party API keys stay server-side (see build.js).
const __ENV = {
    "SUPABASE_URL": "",
    "SUPABASE_ANON_KEY": ""
};
