// Auto-generated by build.js — DO NOT EDIT MANUALLY
// Environment variables injected at build time
const __ENV = {
    SUPABASE_URL: '',
    SUPABASE_ANON_KEY: '',
    FMP_API_KEY: '',
    TWELVE_DATA_API_KEY: '',
    FINNHUB_API_KEY: '',
    FRED_API_KEY: ''
};
