// Auto-generated by build.js — DO NOT EDIT MANUALLY
// Environment variables injected at build time
// NOTE: For local development, these fallback to values from supabase-config.js
const __ENV = {
    SUPABASE_URL: '',
    SUPABASE_ANON_KEY: '',
    FMP_API_KEY: '',
    TWELVE_DATA_API_KEY: '',
    FINNHUB_API_KEY: '',
    FRED_API_KEY: ''
};

// The actual API keys are loaded from supabase-config.js
// This file exists for build-time injection on Vercel/production
