// Build script — generates js/env-config.js from environment variables
// Runs during Vercel build. If env vars are not set, uses empty strings (fallback to defaults in supabase-config.js)

const fs = require('fs');
const path = require('path');

// Clean env var value — strip "KEY=" prefix if accidentally included (common .env import issue)
function cleanEnvValue(key, value) {
    if (!value) return '';
    // Strip "KEY=" prefix if the value starts with it (e.g. "SUPABASE_URL=https://...")
    if (value.startsWith(key + '=')) {
        return value.slice(key.length + 1);
    }
    return value.trim();
}

const keys = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'FMP_API_KEY', 'TWELVE_DATA_API_KEY', 'FINNHUB_API_KEY', 'FRED_API_KEY'];

const envConfig = {};
keys.forEach(key => {
    envConfig[key] = cleanEnvValue(key, process.env[key] || '');
});

const output = `// Auto-generated by build.js — DO NOT EDIT MANUALLY
// Environment variables injected at build time
const __ENV = ${JSON.stringify(envConfig, null, 4)};
`;

const outPath = path.join(__dirname, 'js', 'env-config.js');
fs.writeFileSync(outPath, output, 'utf-8');

// Log what was generated (without exposing full keys)
keys.forEach(key => {
    const val = envConfig[key];
    const display = val ? val.substring(0, 12) + '...' : '(empty → fallback)';
    console.log(`  ${key} = ${display}`);
});
console.log('Generated js/env-config.js');
