// Build script — generates js/env-config.js from environment variables
// Runs during Vercel build. If env vars are not set, uses empty strings (fallback to defaults in supabase-config.js)

const fs = require('fs');
const path = require('path');

const envConfig = {
    SUPABASE_URL: process.env.SUPABASE_URL || '',
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || '',
    FMP_API_KEY: process.env.FMP_API_KEY || '',
    TWELVE_DATA_API_KEY: process.env.TWELVE_DATA_API_KEY || '',
    FINNHUB_API_KEY: process.env.FINNHUB_API_KEY || ''
};

const output = `// Auto-generated by build.js — DO NOT EDIT MANUALLY
// Environment variables injected at build time
const __ENV = ${JSON.stringify(envConfig, null, 4)};
`;

const outPath = path.join(__dirname, 'js', 'env-config.js');
fs.writeFileSync(outPath, output, 'utf-8');
console.log('Generated js/env-config.js');
